FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY provision_distributed.py .
COPY hooks.js .

EXPOSE 9000

CMD ["python", "provision_distributed.py"]
